services:
    discovery-server:
        build: ./discovery-server
        ports: 
            - "8761:8761"
            
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8761"]
          interval: 200s
          timeout: 200s
          retries: 5
    movie-ratings-service:
        build: ./movie-ratings-service
        depends_on:
            discovery-server:
                condition: service_healthy
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080"]
          interval: 200s
          timeout: 200s
          retries: 5
    
    movie-info-service:
        build: ./movie-info-service
        depends_on:
            discovery-server:
                condition: service_healthy
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080"]
          interval: 200s
          timeout: 200s
          retries: 5
        
    movie-catalog-service:
        build: ./movie-catalog-service
        ports:
            - "8080:8080"
        depends_on:
            movie-info-service:
                condition: service_healthy
            movie-ratings-service:
                condition: service_healthy